### PR TITLE
Modify cmake config to allow use of c-blosc2 as a shared library

### PR DESCRIPTION
**Pull request by mkitti**
This pull request modifies the cmake configuration to allow an installed c-blosc2 shared library to be discovered and used instead of the statically built included c-blosc2 submodule.

This is controlled by the CMake variable `PREFER_BLOSC2_EXTERNAL`. If the search for the external c-blosc2 fails, then the internal sources are used.

This includes a FindBLOSC2.cmake module for finding c-blosc2.

Shared library use depends on https://github.com/Blosc/c-blosc2/pull/328 in order to build the example example_empty_shape.c which uses `blosc2_schunk_fill_special`.

Note the c-blosc2 submodule has not been updated. Using an externally built c-blosc2 static library may require additional work depending on how the c-blosc2 library was built. Using the internal c-blosc2 submodule is likely the best way to compile with a static library.

### CODE REVIEW

**Comment by aleixalcacer** [comment]
First of all, we greatly appreciate the contribution you have made. It looks so good!

However, we would like to discuss a few things. We decided to use blosc as a static library (and as a submodule) to make sure caterva uses the proper version of it and to avoid having binary dependencies.

We know that if we use a static linking, the Caterva binary will be larger, but we do not see any other inconvenience. Can you tell us the benefits you found linking against a shared c-blosc2 library?

**Comment by mkitti** [comment]
Part of my motivation for building caterva was to package it for the Julia ecosystem via binarybuilder.org along side c-blosc2 so that I could begin experimenting with it from Julia.
https://github.com/JuliaPackaging/Yggdrasil/blob/master/B/Blosc2/build_tarballs.jl
https://github.com/JuliaBinaryWrappers/Blosc2_jll.jl

What would happen if one loaded both libcaterva.so with c-blosc2 statically integrated and libblosc2.so at the same time?

From the packaging perspective where one can manage the binary dependency, having the smaller non-conflicting shared libraries would be advantageous.

**Comment by mkitti** [comment]
Looking at nm I guess libcaterva.so doesn't export any blosc2 symbols, so I suppose there should not be a conflict.

**Comment by aleixalcacer** [comment]
You're right, no blosc symbols are exported in caterva. However, we agree that this PR will make the library more complete. So, I'm going to merge it! :)

**Comment by aleixalcacer** [comment]
Note that the `PREFER_BLOSC2_EXTERNAL` name has changed to `CATERVA_PREFER_BLOSC2_EXTERNAL` to homogenize all the option names. See #77.

**Pull request merged**
