### PR TITLE
sequencial → sequential

### LINKED ISSUE #89: sequencial → sequential
This typo needs to be fixed across all the sources.

Unfortunately, the change will break the API back-compatibility, but I feel it's early enough in the project to break it.

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes #89.

Not sure if there is an easy way to keep API back-compatibility.

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Thanks for bringing this to our attention.  And yes, I think we are still on time to change the API without too much hassle (the library has not get too much adoption yet).  I am pondering that it might be better to rename this to `contiguous` so as to match the Blosc2 parlance.

**Comment by DimitriPapadopoulos** [comment]
OK, do you want me to change it to `contiguous` both in the C library (#91) and the Python module (https://github.com/Blosc/python-caterva/pull/44)?

**Comment by FrancescAlted** [comment]
> OK, do you want me to change it to `contiguous` both in the C library (#91) and the Python module ([Blosc/python-caterva#44](https://github.com/Blosc/python-caterva/pull/44))?

No need.  Let us discuss this before doing anything.

**Comment by FrancescAlted** [comment]
Changed "sequencial" to "contiguous" in #110. Closing.

**Pull request closed without merging**
