### PR TITLE
Frame generator

### PR DESCRIPTION
**Pull request by oscargm98**
New frames added

### CODE REVIEW

**Comment by oscargm98** [comment]
I have added some lines to an example of Master but now in the PR it seems like if I had deleted the old one and added a new .c

**Review by FrancescAlted — COMMENTED** [review]
It looks good to me.  For resolving the conflict, I suggest to remove the file with a commit, and replace it again (of course, do a backup of the file first ;-).  That should fix the issue.

**Comment by oscargm98** [comment]
I have deleted and replaced the .c and merged master into this one and now in "Files changed" everything does look OK, but now we still can not merge the PR if we want due to unknown conflicts

**Comment by FrancescAlted** [comment]
Ok.  So the last resort solution is to ditch this PR completely and create a new one.  Fortunately, this is just one file, so quite easy to do.

**Pull request closed without merging**
